config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    resources :comments
  end
  
  resources :users
  
  get "/:slug", :controller => "home", :action => "slug", :as => :slug 

  get "/auth/login", :controller => "auth", :action => "index"
  post "/auth/login", :controller => "auth", :action => "login"
  get "/auth/logout", :controller => "auth", :action => "logout"

  post "/metrix/click", :controller => "metrix", :action => "click"
  root 'home#index'
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  validates :commenter, :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :destroy]
  
  class CommentParams
    def self.build params
      params.require(:comment)[:is_spam] = params.require(:comment)[:honey].to_s != ''
      params.require(:comment).permit(:commenter, :body, :honey, :is_spam)  
    end
  end

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create!(CommentParams.build(params))
    Notifier.notify_about(@article, @comment).deliver
    redirect_to slug_path(@article.slug), notice: 'comment was successfully saved.'  
  end
  
  rescue_from ActiveRecord::RecordInvalid do
    redirect_to slug_path(@article.slug), notice: 'comment was not saved.'
  end

  def index
    @article = Article.find(params[:article_id])
    @comments = @article.comments
  end

  def show
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to article_comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_comment
      begin
        @comment = Comment.find(params[:id])
      rescue Exception => e
        respond_to do |format|
          format.html { redirect_to article_comments_url }
          format.json { head :not_found }
        end
      end
    end
end

app/views/comments/index.html.erb
<h2>Listing comments</h2>

<table>
  <thead>
    <tr>
      <th>Commenter</th>
      <th>Body</th>
      <th>Spam</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.commenter %></td>
        <td><%= comment.body %></td>
        <td><%= comment.is_spam %></td>
        <td>
          <%= link_to 'Show', article_comment_path(@article, comment) %>
        </td>
        <td>
          <%= link_to 'Destroy', article_comment_path(@article, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'Back', articles_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Commenter:</strong>
  <%= @comment.commenter %>
</p>

<p>
  <strong>Text:</strong>
  <%= markdown @comment.body %>
</p>

<p>
  <strong>spam:</strong>
  <%= @comment.is_spam  ? 'yes' : 'no' %>
  (<%= @comment.honey %>)
</p>

<%= link_to 'Back', article_comments_path %>