config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    resources :comments
  end
  
  resources :users
  
  get "/:slug", :controller => "home", :action => "slug", :as => :slug 

  get "/auth/login", :controller => "auth", :action => "index"
  post "/auth/login", :controller => "auth", :action => "login"
  get "/auth/logout", :controller => "auth", :action => "logout"

  post "/metrix/click", :controller => "metrix", :action => "click"
  root 'home#index'
  
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  def self.most_recent
    articles = Article.published_latest_first
    if articles.empty?
      Article.no_articles
    else
      @article = articles[0]
    end
  end

  def self.published_latest_first
    Article.where('published_at IS NOT NULL')
           .where('published_at <= ?', Date.today)
           .order('published_at DESC')
  end

  def self.no_articles
    Article.new(:title => "no article", :text => "yet")
  end

  def self.not_found 
    Article.new(:title => "not found", :text => "")
  end
  
  def ==(other)
    if defined? other.title and defined? other.text
      self.title == other.title and self.text == other.text
    elsif self.title and self.text
      false
    else
      true
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_filter :check_authorization

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show 
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      begin
        @article = Article.find(params[:id])
      rescue Exception => e
        respond_to do |format|
          format.html { redirect_to articles_url }
          format.json { head :not_found }
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      permitted = params.require(:article).permit(:title, :text, :published_at, :user_id)
      permitted[:slug] = Blog::Slugr.exec permitted[:title]
      permitted
    end
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text, :cols => "30", :rows => "30"%>
  </div>
  <div class="field">
    <%= f.label :published_at %><br>
    <%= f.date_field :published_at, {:include_blank => true, :default => nil} %>
  </div>
  <div class="field">
    <%= f.label :user %><br>
    <%= f.select :user_id, options_for_select(User.all.map{|s|[s.username, s.id]}) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h2>Editing article</h2>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h2>Listing articles</h2>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Slug</th>
      <th>Author</th>
      <th>Published</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.slug %></td>
        <td><%= article.user ? article.user.username : 'unknown' %></td>
        <td>
          <% if article.published_at == nil %>
            -
          <% elsif %>
            <%= article.published_at %>
          <% end %>
        </td>
        <td><%= link_to article.comments.size, article_comments_path(article) %></a></td>
        <td><%= link_to 'Show', article.slug %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h2>New article</h2>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= markdown @article.text %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @article.slug %>
</p>

<p>
  <strong>Published:</strong>
  <% if @article.published_at == nil %>
    -
  <% elsif %>
    <%= @article.published_at %>
  <% end %>
</p>

<p>
    <strong>By:</strong>
    <%= @article.user ? @article.user.username : 'unknown' %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>